name: C/C++ CI
on: release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: prerequisite
      run: sudo apt-get install -y libkrb5-dev
    - name: submodule
      run: git submodule update --init --recursive
    - name: make
      run: make
    
