name: C/C++ CI
on: release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: |
        sudo apt update
        sudo apt-get install python3.9
        sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.9 get-pip.py
    - name: submodule
      run: git submodule update --init --recursive
    - name: make
      run: make
    
