name: C/C++ CI

on: release

jobs:
  build:

    runs-on: ubi8

    steps:
    - uses: actions/checkout@v3
    - name: install
      run: yum install -y python39 python39-pip
    - name: submodule
      run: git submodule update --init --recursive
    - name: make
      run: make
    
